In [2]:
import torch
# print(torch.cuda.is_available())
# print(torch.cuda.get_device_name(0))

In [ ]:
from utils.data_generator_discrete import *
dir_path = "/Users/yamashitanatsuki/Documents/Python/CTMCxDeepSets"
name = "test_base"
sumples = 10000
TRMG = DiagonalTransitionRateMatrixGenerator(4)
trm = TRMG.generateMatrix(TRMG.setDiagonalElement_byLifespan,100)
dg = DataGenerator(trm, sumples,)

d = DirichletDeltaT(min_intervals=2, max_intervals=10)
M = dg.generate_matrix(d.sample)
dg.generate_dataFile(M,name,dir_path)

In [17]:
import pandas as pd
df = pd.read_csv("notebooks/deck.csv",header=None)
display(df.head())

          0         1          2
0  0.021916  0.136360   0.101534
1  0.022061  0.140803   0.101830
2  1.000000  1.000000  22.000000
3  1.000000  1.000000   2.000000
4  1.000000  1.000000   1.000000

In [16]:
df = df[df[0]==4]
display(df.head())

Empty DataFrame
Columns: [0, 1, 2]
Index: []